name: DP-ItemEditor
version: 2.0.0
main: com.darksoldier1404.die.ItemEditor
authors: [ DEAD_POOLIO_ ]
api-version: 1.16
depend:
  - DPP-Core
commands:
  dpie:
    aliases: [ dpitemeditor, itemeditor, ie ]